### ISSUE TITLE
Code review #1

### ISSUE THREAD

**Issue by KineticCookie** [Ainaz/Float-Mass#1]
1. `.gitignore` нехватает.
2. Незачем создавать два объекта `Random`. Один прекрасно справится.
3. Что за !@#$% творится в строке 25?
4. Нужен ОДИН метод, а ты реализовал 3.

Исправляй. 

---
Deadline - неделя.

**Comment by KineticCookie** [comment]
Как исправишь что-нибудь, отпишись здесь, и напиши id коммита.
Например:
Исправил 2 пункт. Коммит: cd2634c

**Comment by Ainaz** [comment]
ок

**Comment by Ainaz** [comment]
Исправил 1 пункт 2a3d15596b6630e7cb73124faa01ca15dedf57ed

**Comment by KineticCookie** [comment]
Кстати, кроме  добавления `.gitignore` нужно будет убрать мусорные папки. `bin`и `obj` например.

**Comment by Ainaz** [comment]
Исправил все, кроме .gitignore 5f8dedfc3579fa9313ac1af4e879cd0412b9e067

**Comment by Ainaz** [comment]
Исправил последнее замечание и убрал ненужные бинарники из репозитория номер коммита: 109d8484b08d0f05276d467145b30efda60220b9

**Comment by KineticCookie** [comment]
Отлично. Теперь смерджь в `master`.

**Comment by KineticCookie** [comment]
Нормально. Закрываю issue.
